-- KB Stylish - Test Enablement Package: Seed Reviews & Votes
-- Run in Supabase SQL editor or psql as a privileged role

WITH delivered AS (
  SELECT o.id AS order_id, o.user_id, oi.product_id
  FROM public.orders o
  JOIN public.order_items oi ON oi.order_id = o.id
  WHERE o.status IN ('delivered','completed')
  ORDER BY o.created_at DESC
  LIMIT 5
), inserted AS (
  INSERT INTO public.reviews (
    product_id, user_id, order_id, order_item_id, rating, title, comment,
    is_approved, moderation_status, created_at, updated_at
  )
  SELECT 
    d.product_id, d.user_id, d.order_id,
    (SELECT id FROM public.order_items WHERE order_id = d.order_id AND product_id = d.product_id LIMIT 1),
    (1 + (random()*4)::int),
    'Great product', 'Autogenerated review for testing',
    true, 'approved', now(), now()
  FROM delivered d
  ON CONFLICT DO NOTHING
  RETURNING id
)
INSERT INTO public.review_votes (review_id, user_id, vote_type, created_at, updated_at)
SELECT 
  i.id,
  (SELECT id FROM public.user_profiles ORDER BY random() LIMIT 1),
  CASE WHEN random() < 0.8 THEN 'helpful' ELSE 'unhelpful' END,
  now(), now()
FROM inserted i
ON CONFLICT DO NOTHING;
